[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "pgfenicsx"
version = "0.1.0"
description = ""
authors = [{ name = "Moritz Feuerle" }]
readme = "README.md"
requires-python = ">=3.12"