name: Build and Deploy Docs

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Merge environment files
        run: |
          cp environment.yml environment-combined.yml
          echo "Base Conda File:"
          cat environment-combined.yml
          echo "Sphinx Conda File:"
          cat docs/environment-sphinx.yml
          # extract dependencies from docs/environment-sphinx.yml
          awk '/dependencies:/ {flag=1; next} /^([^[:space:]]|$)/ {flag=0} flag {print}' docs/environment-sphinx.yml >> environment-combined.yml
          echo "Combined Conda File:"
          cat environment-combined.yml

      - name: Set up micromamba
        uses: mamba-org/setup-micromamba@v2
        with:
          environment-name: docs
          environment-file: environment-combined.yml
          cache-environment: true
          cache-environment-key: "env-${{ hashFiles('environment.yml', 'docs/environment-sphinx.yml') }}"
          create-args: >-
            python=3.12

      - name: Install pgfenicsx
        shell: bash -l {0}
        run: pip install .

      - name: Build HTML
        working-directory: docs
        shell: bash -l {0}
        run: make html

      - name: Upload artifact for Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: docs/_build/html

  deploy:
    needs: build
    runs-on: ubuntu-latest

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
